import {
  archiveProject,
  createProject,
  createProjectInOwnOrganization,
  getProjectForMember,
  getProjectForOrganization,
  listArchivedProjects,
  listProjects,
  listProjectsEnsuringOne,
  listProjectsForMemberEnsuringOne,
  restoreProject,
  setProjectDomain,
  setProjectMarket,
  updateProject,
} from "@/server/features/projects/services/projects";

export const ProjectService = {
  listProjects,
  listProjectsEnsuringOne,
  listProjectsForMemberEnsuringOne,
  createProject,
  createProjectInOwnOrganization,
  updateProject,
  setProjectDomain,
  setProjectMarket,
  archiveProject,
  restoreProject,
  listArchivedProjects,
  getProjectForOrganization,
  getProjectForMember,
} as const;
